face_features = {
'face000.bmp' 'Male'   'Blue'  ;
'face001.bmp' 'Male'   'Blue'  ;
'face002.bmp' 'Male'   'Blue'  ;
'face003.bmp' 'Male'   'Blue'  ;
'face004.bmp' 'Male'   'Blue'  ;
'face005.bmp' 'Male'   'Blue'  ;
'face006.bmp' 'Male'   'Blue'  ;
'face007.bmp' 'Female' 'Brown' ;
'face008.bmp' 'Male'   'Blue'  ;
'face009.bmp' 'Male'   'Blue'  ;
'face010.bmp' 'Male'   'Blue'  ;
'face011.bmp' 'Male'   'Blue'  ;
'face012.bmp' 'Female' 'Blue'  ;
'face013.bmp' 'Female' 'Blue'  ;
'face014.bmp' 'Female' 'Blue'  ;
'face015.bmp' 'Female' 'Brown' ;
'face016.bmp' 'Female' 'Brown' ;
'face017.bmp' 'Female' 'Brown' ;
'face018.bmp' 'Female' 'Brown' ;
'face019.bmp' 'Female' 'Brown' ;
'face020.bmp' 'Female' 'Brown' ;
'face021.bmp' 'Female' 'Brown' ;
'face022.bmp' 'Female' 'Brown' ;
'face023.bmp' 'Female' 'Brown' ;
'face024.bmp' 'Female' 'Brown' ;
'face025.bmp' 'Female' 'Brown' ;
'face026.bmp' 'Female' 'Brown' ;
'face027.bmp' 'Female' 'Brown' ;
'face028.bmp' 'Female' 'Brown' ;
'face029.bmp' 'Female' 'Brown' ;
'face030.bmp' 'Female' 'Brown' ;
'face031.bmp' 'Female' 'Blue'  ;
'face032.bmp' 'Female' 'Brown' ;
'face033.bmp' 'Female' 'Brown' ;
'face034.bmp' 'Female' 'Brown' ;
'face035.bmp' 'Female' 'Brown' ;
'face036.bmp' 'Female' 'Brown' ;
'face037.bmp' 'Female' 'Brown' ;
'face038.bmp' 'Female' 'Blue'  ;
'face039.bmp' 'Male'   'Blue'  ;
'face040.bmp' 'Male'   'Blue'  ;
'face041.bmp' 'Female' 'Blue'  ;
'face042.bmp' 'Male'   'Blue'  ;
'face043.bmp' 'Female' 'Blue'  ;
'face044.bmp' 'Male'   'Brown' ;
'face045.bmp' 'Male'   'Brown' ;
'face046.bmp' 'Male'   'Brown' ;
'face047.bmp' 'Male'   'Brown' ;
'face048.bmp' 'Male'   'Brown' ;
'face049.bmp' 'Male'   'Brown' ;
'face050.bmp' 'Male'   'Brown' ;
'face051.bmp' 'Male'   'Brown' ;
'face052.bmp' 'Male'   'Brown' ;
'face053.bmp' 'Male'   'Brown' ;
'face054.bmp' 'Male'   'Brown' ;
'face055.bmp' 'Male'   'Brown' ;
'face056.bmp' 'Male'   'Brown' ;
'face057.bmp' 'Male'   'Blue'  ;
'face058.bmp' 'Male'   'Blue'  ;
'face059.bmp' 'Male'   'Brown' ;
'face060.bmp' 'Male'   'Brown' ;
'face061.bmp' 'Male'   'Brown' ;
'face062.bmp' 'Male'   'Blue'  ;
'face063.bmp' 'Male'   'Blue'  ;
'face064.bmp' 'Male'   'Brown' ;
'face065.bmp' 'Male'   'Blue'  ;
'face066.bmp' 'Male'   'Blue'  ;
'face067.bmp' 'Male'   'Blue'  ;
'face068.bmp' 'Male'   'Blue'  ;
'face069.bmp' 'Male'   'Blue'  ;
'face070.bmp' 'Female' 'Blue'  ;
'face071.bmp' 'Female' 'Blue'  ;
'face072.bmp' 'Female' 'Blue'  ;
'face073.bmp' 'Female' 'Brown' ;
'face074.bmp' 'Female' 'Brown' ;
'face075.bmp' 'Female' 'Blue'  ;
'face076.bmp' 'Female' 'Brown' ;
'face077.bmp' 'Female' 'Brown' ;
'face078.bmp' 'Female' 'Blue'  ;
'face079.bmp' 'Female' 'Brown' ;
'face080.bmp' 'Female' 'Blue'  ;
'face081.bmp' 'Female' 'Brown' ;
'face082.bmp' 'Female' 'Brown' ;
'face083.bmp' 'Female' 'Brown' ;
'face084.bmp' 'Female' 'Brown' ;
'face085.bmp' 'Female' 'Brown' ;
'face086.bmp' 'Female' 'Brown' ;
'face087.bmp' 'Female' 'Brown' ;
'face088.bmp' 'Male'   'Brown' ;
'face089.bmp' 'Male'   'Brown' ;
'face090.bmp' 'Male'   'Blue'  ;
'face091.bmp' 'Male'   'Blue'  ;
'face092.bmp' 'Female' 'Brown' ;
'face093.bmp' 'Male'   'Blue'  ;
'face094.bmp' 'Male'   'Brown' ;
'face095.bmp' 'Male'   'Brown' ;
'face096.bmp' 'Female' 'Brown' ;
'face097.bmp' 'Male'   'Blue'  ;
'face098.bmp' 'Male'   'Brown' ;
'face099.bmp' 'Male'   'Blue'  ;
'face100.bmp' 'Male'   'Blue'  ;
'face101.bmp' 'Male'   'Blue'  ;
'face102.bmp' 'Male'   'Blue'  ;
'face103.bmp' 'Male'   'Blue'  ;
'face104.bmp' 'Female' 'Brown' ;
'face105.bmp' 'Female' 'Brown' ;
'face106.bmp' 'Female' 'Brown' ;
'face107.bmp' 'Female' 'Brown' ;
'face108.bmp' 'Female' 'Brown' ;
'face109.bmp' 'Female' 'Brown' ;
'face110.bmp' 'Female' 'Brown' ;
'face111.bmp' 'Female' 'Brown' ;
'face112.bmp' 'Female' 'Brown' ;
'face113.bmp' 'Female' 'Brown' ;
'face114.bmp' 'Female' 'Brown' ;
'face115.bmp' 'Female' 'Brown' ;
'face116.bmp' 'Female' 'Brown' ;
'face117.bmp' 'Female' 'Brown' ;
'face118.bmp' 'Female' 'Brown' ;
'face119.bmp' 'Female' 'Brown' ;
'face120.bmp' 'Female' 'Brown' ;
'face121.bmp' 'Female' 'Blue'  ;
'face122.bmp' 'Female' 'Blue'  ;
'face123.bmp' 'Female' 'Brown' ;
'face124.bmp' 'Female' 'Brown' ;
'face125.bmp' 'Female' 'Brown' ;
'face126.bmp' 'Female' 'Brown' ;
'face127.bmp' 'Female' 'Brown' ;
'face128.bmp' 'Male'   'Brown' ;
'face129.bmp' 'Male'   'Blue'  ;
'face130.bmp' 'Male'   'Blue'  ;
'face131.bmp' 'Female' 'Blue'  ;
'face132.bmp' 'Female' 'Blue'  ;
'face133.bmp' 'Female' 'Brown' ;
'face134.bmp' 'Male'   'Brown' ;
'face135.bmp' 'Male'   'Brown' ;
'face136.bmp' 'Male'   'Brown' ;
'face137.bmp' 'Male'   'Brown' ;
'face138.bmp' 'Male'   'Brown' ;
'face139.bmp' 'Male'   'Brown' ;
'face140.bmp' 'Male'   'Brown' ;
'face141.bmp' 'Male'   'Brown' ;
'face142.bmp' 'Male'   'Brown' ;
'face143.bmp' 'Male'   'Brown' ;
'face144.bmp' 'Male'   'Brown' ;
'face145.bmp' 'Male'   'Brown' ;
'face146.bmp' 'Male'   'Brown' ;
'face147.bmp' 'Male'   'Brown' ;
'face148.bmp' 'Male'   'Brown' ;
'face149.bmp' 'Male'   'Brown' ;
'face150.bmp' 'Male'   'Brown' ;
'face151.bmp' 'Female' 'Blue'  ;
'face152.bmp' 'Male'   'Blue'  ;
'face153.bmp' 'Female' 'Blue'  ;
'face154.bmp' 'Female' 'Blue'  ;
'face155.bmp' 'Female' 'Brown' ;
'face156.bmp' 'Female' 'Brown' ;
'face157.bmp' 'Female' 'Brown' ;
'face158.bmp' 'Male'   'Blue'  ;
'face159.bmp' 'Male'   'Brown' ;
'face160.bmp' 'Male'   'Blue'  ;
'face161.bmp' 'Female' 'Blue'  ;
'face162.bmp' 'Female' 'Brown' ;
'face163.bmp' 'Female' 'Brown' ;
'face164.bmp' 'Female' 'Brown' ;
'face165.bmp' 'Male'   'Brown' ;
'face166.bmp' 'Female' 'Brown' ;
'face167.bmp' 'Female' 'Brown' ;
'face168.bmp' 'Female' 'Brown' ;
'face169.bmp' 'Female' 'Brown' ;
'face170.bmp' 'Female' 'Brown' ;
'face171.bmp' 'Female' 'Blue'  ;
'face172.bmp' 'Female' 'Blue'  ;
'face173.bmp' 'Female' 'Brown' ;
'face174.bmp' 'Female' 'Brown' ;
'face175.bmp' 'Female' 'Brown' ;
'face176.bmp' 'Female' 'Blue'  ;
'face177.bmp' 'Female' 'Brown' 
}

n = size(face_features,1);  % should be 177
p = size(face_features,2);  % should be 3

face_features_numeric = zeros(n,p);
for i=1:n
   face_features_numeric(i,1) = i;
   if strcmp(face_features(i,2), 'Female')
      face_features_numeric(i,2) = 1;
   end
   if strcmp(face_features(i,3), 'Brown')
      face_features_numeric(i,3) = 1;
   end
end

% unusual images that can mess up the eigenstructure:
image_to_omit = {
'face011.bmp'  'strange face' ;
'face021.bmp'  'strange face' ;
'face127.bmp'  'strange face' ;
'face128.bmp'  'strange face' ;
'face024.bmp'  'teeth are showing' ;
'face094.bmp'  'teeth are showing' ;
'face128.bmp'  'teeth are showing' ;
'face135.bmp'  'teeth are showing' ;
'face147.bmp'  'teeth are showing' ;
'face150.bmp'  'teeth are showing' }
